### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by youngsasa2021** [wuyike2000/Retrieve-Rewrite-Answer#10]
您好！非常感谢作者在论文以及代码中提供的新思路，目前我在做自己的疾病知识图谱，也希望用到代码进行KG-to-Text的工作。目前关于数据集上有一些疑问，我是根据ZJQA这个数据集进行自己数据的构建的
1.indexes/triple.txt（三元组）
2.KG-to-text/data：请问是用corpus_generation.py去做的吗？
3.data/:(问题，头实体，关系，尾实体，一个数字)，请问这个数字是指什么意思呀？是指一跳两跳吗？
谁参加了第18届亚运会乒乓球比赛混双决赛	第18届亚运会	项目|成员	孙颖莎	2 这个2是什么意思？我该怎么制作这个数据集比较好？
期待您的指导意见！

**Comment by wuyike2000** [comment]
最后的数字是指问题的跳数
