### ISSUE TITLE
llama微调问题

### ISSUE THREAD

**Issue by Yclock** [wuyike2000/Retrieve-Rewrite-Answer#11]
基础模型为Chinese-Alpaca-2-7B，使用4090微调，batch_size修改为1仍然报错CUDA out of memory，我想问下最少需要多少内存？

**Comment by youngsasa2021** [comment]
您好，我也出现了这个问题，同样也将batch_size设置为1，两张4090,但是还是cuda out of memory。可以交流一下吗？

**Comment by Yclock** [comment]
> 您好，我也出现了这个问题，同样也将batch_size设置为1，两张4090,但是还是cuda out of memory。可以交流一下吗？

我暂时还没有解决，请问您发现是哪里出问题了吗？还是确实就是内存不够？

**Comment by wuyike2000** [comment]
能否给出具体的设置吗？就是run_sft_chat_chinese-7b.sh这个文件

**Comment by Yclock** [comment]
> 能否给出具体的设置吗？就是run_sft_chat_chinese-7b.sh这个文件

您好，我的设置如下，主要更改了model等位置以及batch_size：
lr=1e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/home/leike/models/chinese-alpaca-2-7b
chinese_tokenizer_path=/home/leike/models/chinese-alpaca-2-7b
dataset_dir=JWQA/train/
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
output_dir=output-JWQA/alpaca-7b
validation_file=JWQA/dev.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --master_port 29501 --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft-chinese-7b.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed 1234 \
    --fp16 \
    --num_train_epochs 10 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy epoch \
    --save_total_limit 2 \
    --evaluation_strategy epoch \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False \
    --load_best_model_at_end True

**Comment by wuyike2000** [comment]
<img width="807" alt="屏幕截图 2024-08-02 123228" src="https://github.com/user-attachments/assets/de8547de-8f9c-4e9e-b23a-492ca088bee6">
4090可能会存在内存不够的问题，可以考虑降低lora_rank和lora_alpha，以及去掉modules_to_save这个模块的训练

**Comment by Yclock** [comment]
> <img alt="屏幕截图 2024-08-02 123228" width="807" src="https://private-user-images.githubusercontent.com/60560866/354464286-de8547de-8f9c-4e9e-b23a-492ca088bee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTM3NjUsIm5iZiI6MTcyMjc1MzQ2NSwicGF0aCI6Ii82MDU2MDg2Ni8zNTQ0NjQyODYtZGU4NTQ3ZGUtOGY5Yy00ZTllLWIyM2EtNDkyY2EwODhiZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA2Mzc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NzJkMjE2YWJiNTY0ZjA3ZjJmNjE2ZjczODU1NjkwYjAwMzg3ZTE2MjRmNzY5ZTMyMTU1MTcxZjhjOTk0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.br1UbUs8jlMNsJrji3PspGEyksJUXmVqOl347vyg60M"> 4090可能会存在内存不够的问题，可以考虑降低lora_rank和lora_alpha，以及去掉modules_to_save这个模块的训练

好的，我试试，感谢回复
