### ISSUE TITLE
关于MetaQA，请问可以提供有关检索结果的文件吗，类似于WQSP中那样。

### ISSUE THREAD

**Issue by hjs2027864933** [wuyike2000/Retrieve-Rewrite-Answer#7]
或者可以提供微调后的path_prediction模型吗，由于我的计算资源有限，训练1000个epoch需要的时间太久了，期待您的回复，感谢！

**Comment by wuyike2000** [comment]
我更新了README，将检索后的结果放在https://pan.baidu.com/s/1z-LYruiBzAx9P0p6IVsKuQ?pwd=ebut上了。其实不需要训练1000个epoch的，我是通过设置patience来停止训练。
model_args.use_early_stopping=True
model_args.early_stopping_consider_epochs=True
model_args.early_stopping_patience=10

**Comment by hjs2027864933** [comment]
好的，收到了，感谢

**Comment by 247285** [comment]
您好，我在运行webqsp数据集微调llama-chat-7b的时候，结果没有包含hit1指标的结果，在哪里可以看到这个结果呢。
