### ISSUE TITLE
请问这个文件在哪里呀？

### ISSUE THREAD

**Issue by youngsasa2021** [wuyike2000/Retrieve-Rewrite-Answer#9]
Traceback (most recent call last):
  File "retrieve.py", line 5, in <module>
    taildict=pickle.load(open('../../../corpus_generation/ZJQA/indexes/taildict.pkl','rb'))
FileNotFoundError: [Errno 2] No such file or directory: '../../../corpus_generation/ZJQA/indexes/taildict.pkl'

**Comment by wuyike2000** [comment]
您好，这个文件是需要运行脚本生成的。请先到corpus_generation/ZJQA/process/目录下，然后运行process.py生成对应的文件，其中包括了taildict.pkl。

**Comment by WangYQ999** [comment]
您好，processed_data_ZJQA中的文件与ZJQA/KG-to-Text/data中的文件是一样的，是不是processed_data_ZJQA中的数据放错了？

**Comment by youngsasa2021** [comment]
没有诶，我已经跑通了，没有问题



在 2024-06-24 15:55:39，"Yunqiang" ***@***.***> 写道：

您好，processed_data_ZJQA中的文件与ZJQA/KG-to-Text/data中的文件是一样的，是不是processed_data_ZJQA中的数据放错了？
